### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by glennpratt** [jakub-g/gh-code-review-assistant#34]
It looks like there are fixes committed, but unreleased. Could you cut a new release?

**Comment by jakub-g** [comment]
Hi, not sure what you mean exactly; repo is up-to-date and you can update to the newest version (1.0.4) by browsing to:

https://raw.githubusercontent.com/jakub-g/gh-code-review-assistant/next/ghAssistant.user.js

it should have updated automatically if your GM/TM has the auto update enabled.

Though I've noticed this week some CSS issue with styling button, I'll work on it soon.

**Comment by jakub-g** [comment]
1.0.5 released, enjoy
